# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rss_cost_analysis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.type import date_pb2 as google_dot_type_dot_date__pb2
from google.type import money_pb2 as google_dot_type_dot_money__pb2
import rss_client_pb2 as rss__client__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17rss_cost_analysis.proto\x12\x03RSS\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16google/type/date.proto\x1a\x17google/type/money.proto\x1a\x10rss_client.proto\"\xf2\x03\n\x14\x43ostEstimationReport\x12\n\n\x02id\x18\x01 \x01(\x05\x12\'\n\x0brepair_cost\x18\x02 \x01(\x0b\x32\x12.google.type.Money\x12\x13\n\x0bis_repaired\x18\x03 \x01(\x08\x12\x14\n\x0creport_count\x18\x04 \x01(\x05\x12>\n\x0b\x64\x61mage_dims\x18\x05 \x01(\x0b\x32).RSS.CostEstimationReport.DamageDimension\x12-\n\x12\x64\x61te_of_estimation\x18\x06 \x01(\x0b\x32\x11.google.type.Date\x12\x36\n\x12time_of_estimation\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\x13\x65st_repair_deadline\x18\x08 \x01(\x0b\x32\x11.google.type.Date\x12,\n\x08location\x18\t \x01(\x0b\x32\x1a.RSS.Client.DamageLocation\x1a?\n\x0f\x44\x61mageDimension\x12\x0e\n\x06length\x18\x01 \x01(\x01\x12\r\n\x05width\x18\x02 \x01(\x01\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x01\"4\n\x0cReportFormat\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03PDF\x10\x01\x12\x07\n\x03\x43SV\x10\x02\x12\x08\n\x04JSON\x10\x03\x42\x15\n\x0f\x63om.example.rssH\x01P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rss_cost_analysis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017com.example.rssH\001P\001'
  _globals['_COSTESTIMATIONREPORT']._serialized_start=133
  _globals['_COSTESTIMATIONREPORT']._serialized_end=631
  _globals['_COSTESTIMATIONREPORT_DAMAGEDIMENSION']._serialized_start=514
  _globals['_COSTESTIMATIONREPORT_DAMAGEDIMENSION']._serialized_end=577
  _globals['_COSTESTIMATIONREPORT_REPORTFORMAT']._serialized_start=579
  _globals['_COSTESTIMATIONREPORT_REPORTFORMAT']._serialized_end=631
# @@protoc_insertion_point(module_scope)
