# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rss_cost_analysis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.type import date_pb2 as google_dot_type_dot_date__pb2
from google.type import money_pb2 as google_dot_type_dot_money__pb2
import rss_client_pb2 as rss__client__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rss_cost_analysis.proto',
  package='RSS',
  syntax='proto3',
  serialized_options=_b('\n\026com.example.rss_clientH\001P\001'),
  serialized_pb=_b('\n\x17rss_cost_analysis.proto\x12\x03RSS\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16google/type/date.proto\x1a\x17google/type/money.proto\x1a\x10rss_client.proto\"\xf2\x03\n\x14\x43ostEstimationReport\x12\n\n\x02id\x18\x01 \x01(\x05\x12\'\n\x0brepair_cost\x18\x02 \x01(\x0b\x32\x12.google.type.Money\x12\x13\n\x0bis_repaired\x18\x03 \x01(\x08\x12\x14\n\x0creport_count\x18\x04 \x01(\x05\x12>\n\x0b\x64\x61mage_dims\x18\x05 \x01(\x0b\x32).RSS.CostEstimationReport.DamageDimension\x12-\n\x12\x64\x61te_of_estimation\x18\x06 \x01(\x0b\x32\x11.google.type.Date\x12\x36\n\x12time_of_estimation\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\x13\x65st_repair_deadline\x18\x08 \x01(\x0b\x32\x11.google.type.Date\x12,\n\x08location\x18\t \x01(\x0b\x32\x1a.RSS.Client.DamageLocation\x1a?\n\x0f\x44\x61mageDimension\x12\x0e\n\x06length\x18\x01 \x01(\x01\x12\r\n\x05width\x18\x02 \x01(\x01\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x01\"4\n\x0cReportFormat\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03PDF\x10\x01\x12\x07\n\x03\x43SV\x10\x02\x12\x08\n\x04JSON\x10\x03\x42\x1c\n\x16\x63om.example.rss_clientH\x01P\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_type_dot_date__pb2.DESCRIPTOR,google_dot_type_dot_money__pb2.DESCRIPTOR,rss__client__pb2.DESCRIPTOR,])



_COSTESTIMATIONREPORT_REPORTFORMAT = _descriptor.EnumDescriptor(
  name='ReportFormat',
  full_name='RSS.CostEstimationReport.ReportFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PDF', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CSV', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JSON', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=579,
  serialized_end=631,
)
_sym_db.RegisterEnumDescriptor(_COSTESTIMATIONREPORT_REPORTFORMAT)


_COSTESTIMATIONREPORT_DAMAGEDIMENSION = _descriptor.Descriptor(
  name='DamageDimension',
  full_name='RSS.CostEstimationReport.DamageDimension',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='RSS.CostEstimationReport.DamageDimension.length', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='RSS.CostEstimationReport.DamageDimension.width', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth', full_name='RSS.CostEstimationReport.DamageDimension.depth', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=577,
)

_COSTESTIMATIONREPORT = _descriptor.Descriptor(
  name='CostEstimationReport',
  full_name='RSS.CostEstimationReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RSS.CostEstimationReport.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repair_cost', full_name='RSS.CostEstimationReport.repair_cost', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_repaired', full_name='RSS.CostEstimationReport.is_repaired', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='report_count', full_name='RSS.CostEstimationReport.report_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='damage_dims', full_name='RSS.CostEstimationReport.damage_dims', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_of_estimation', full_name='RSS.CostEstimationReport.date_of_estimation', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_of_estimation', full_name='RSS.CostEstimationReport.time_of_estimation', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='est_repair_deadline', full_name='RSS.CostEstimationReport.est_repair_deadline', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='RSS.CostEstimationReport.location', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COSTESTIMATIONREPORT_DAMAGEDIMENSION, ],
  enum_types=[
    _COSTESTIMATIONREPORT_REPORTFORMAT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=631,
)

_COSTESTIMATIONREPORT_DAMAGEDIMENSION.containing_type = _COSTESTIMATIONREPORT
_COSTESTIMATIONREPORT.fields_by_name['repair_cost'].message_type = google_dot_type_dot_money__pb2._MONEY
_COSTESTIMATIONREPORT.fields_by_name['damage_dims'].message_type = _COSTESTIMATIONREPORT_DAMAGEDIMENSION
_COSTESTIMATIONREPORT.fields_by_name['date_of_estimation'].message_type = google_dot_type_dot_date__pb2._DATE
_COSTESTIMATIONREPORT.fields_by_name['time_of_estimation'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_COSTESTIMATIONREPORT.fields_by_name['est_repair_deadline'].message_type = google_dot_type_dot_date__pb2._DATE
_COSTESTIMATIONREPORT.fields_by_name['location'].message_type = rss__client__pb2._CLIENT_DAMAGELOCATION
_COSTESTIMATIONREPORT_REPORTFORMAT.containing_type = _COSTESTIMATIONREPORT
DESCRIPTOR.message_types_by_name['CostEstimationReport'] = _COSTESTIMATIONREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CostEstimationReport = _reflection.GeneratedProtocolMessageType('CostEstimationReport', (_message.Message,), dict(

  DamageDimension = _reflection.GeneratedProtocolMessageType('DamageDimension', (_message.Message,), dict(
    DESCRIPTOR = _COSTESTIMATIONREPORT_DAMAGEDIMENSION,
    __module__ = 'rss_cost_analysis_pb2'
    # @@protoc_insertion_point(class_scope:RSS.CostEstimationReport.DamageDimension)
    ))
  ,
  DESCRIPTOR = _COSTESTIMATIONREPORT,
  __module__ = 'rss_cost_analysis_pb2'
  # @@protoc_insertion_point(class_scope:RSS.CostEstimationReport)
  ))
_sym_db.RegisterMessage(CostEstimationReport)
_sym_db.RegisterMessage(CostEstimationReport.DamageDimension)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
