# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rss_payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import rss_cost_analysis_pb2 as rss__cost__analysis__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rss_payload.proto',
  package='RSS',
  syntax='proto3',
  serialized_options=_b('\n\026com.example.rss_clientH\001P\001'),
  serialized_pb=_b('\n\x11rss_payload.proto\x12\x03RSS\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17rss_cost_analysis.proto\"\xe7\x01\n\nRSSPayload\x12\x13\n\x0b\x64\x61mage_type\x18\x01 \x03(\t\x12\x14\n\x0csurface_type\x18\x02 \x03(\t\"K\n\x0b\x44\x61mageLevel\x12\x13\n\x0fLVL_UNSPECIFIED\x10\x00\x12\x0b\n\x07LVL_LOW\x10\x01\x12\x0b\n\x07LVL_MED\x10\x02\x12\r\n\tLVL_HEAVY\x10\x03\"a\n\x0eRepairPriority\x12\x18\n\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n\x0cPRIORITY_LOW\x10\x01\x12\x10\n\x0cPRIORITY_MED\x10\x02\x12\x11\n\rPRIORITY_HIGH\x10\x03\x42\x1c\n\x16\x63om.example.rss_clientH\x01P\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,rss__cost__analysis__pb2.DESCRIPTOR,])



_RSSPAYLOAD_DAMAGELEVEL = _descriptor.EnumDescriptor(
  name='DamageLevel',
  full_name='RSS.RSSPayload.DamageLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LVL_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LVL_LOW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LVL_MED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LVL_HEAVY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=142,
  serialized_end=217,
)
_sym_db.RegisterEnumDescriptor(_RSSPAYLOAD_DAMAGELEVEL)

_RSSPAYLOAD_REPAIRPRIORITY = _descriptor.EnumDescriptor(
  name='RepairPriority',
  full_name='RSS.RSSPayload.RepairPriority',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRIORITY_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRIORITY_LOW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRIORITY_MED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRIORITY_HIGH', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=219,
  serialized_end=316,
)
_sym_db.RegisterEnumDescriptor(_RSSPAYLOAD_REPAIRPRIORITY)


_RSSPAYLOAD = _descriptor.Descriptor(
  name='RSSPayload',
  full_name='RSS.RSSPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='damage_type', full_name='RSS.RSSPayload.damage_type', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='surface_type', full_name='RSS.RSSPayload.surface_type', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RSSPAYLOAD_DAMAGELEVEL,
    _RSSPAYLOAD_REPAIRPRIORITY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=316,
)

_RSSPAYLOAD_DAMAGELEVEL.containing_type = _RSSPAYLOAD
_RSSPAYLOAD_REPAIRPRIORITY.containing_type = _RSSPAYLOAD
DESCRIPTOR.message_types_by_name['RSSPayload'] = _RSSPAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RSSPayload = _reflection.GeneratedProtocolMessageType('RSSPayload', (_message.Message,), dict(
  DESCRIPTOR = _RSSPAYLOAD,
  __module__ = 'rss_payload_pb2'
  # @@protoc_insertion_point(class_scope:RSS.RSSPayload)
  ))
_sym_db.RegisterMessage(RSSPayload)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
