name: My Workflow
on: [push, pull_request]
env:
  envFile: .env
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      env:
        PYTHONPATH: ${{ secrets.PYTHONPATH }}
      run: |
        envsubst < $envFile > .env
        source .env
        echo $PYTHONPATH
